# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.5"
manifest_format = "2.0"
project_hash = "1449de974e1f68a7018904cd08fd6f48a563b6bc"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
